# Generated by Django 6.0.4 on 2026-06-13 16:17

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('breed_name', models.CharField(max_length=100)),
                ('tag_id', models.IntegerField(unique=True)),
                ('animal_type', models.CharField(max_length=20)),
                ('age', models.IntegerField()),
                ('dob', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('mk', 'milking'), ('dy', 'dry'), ('sd', 'sold')], default='sd', max_length=2)),
            ],
            options={
                'ordering': ['-dob'],
                'indexes': [models.Index(fields=['-dob'], name='Animals_ani_dob_e23410_idx')],
            },
        ),
    ]
