# Generated by Django 6.0.4 on 2026-06-13 16:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Animals', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Milk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('morning_qty', models.FloatField(default=0)),
                ('evening_qty', models.FloatField(default=0)),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Animals.animal')),
            ],
            options={
                'ordering': ['-date'],
                'indexes': [models.Index(fields=['-date'], name='Milk_milk_date_175dd3_idx')],
            },
        ),
    ]
