# Generated by Django 6.0.4 on 2026-06-14 16:06

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Milk', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='milk',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
