# Generated by Django 6.0.4 on 2026-06-14 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Milk', '0002_alter_milk_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='milk',
            name='total_qty',
            field=models.FloatField(default=0),
        ),
    ]
