# Generated by Django 6.0.4 on 2026-06-13 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('amount', models.IntegerField()),
                ('expense_type', models.CharField(choices=[('fd', 'feed'), ('md', 'medicine'), ('mn', 'mentainance'), ('ot', 'others')], default='fd', max_length=2)),
            ],
            options={
                'ordering': ['-amount'],
                'indexes': [models.Index(fields=['-amount'], name='Expense_exp_amount_a0a26b_idx')],
            },
        ),
    ]
