# Generated by Django 6.0.4 on 2026-06-13 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty_sold', models.IntegerField()),
                ('price', models.IntegerField()),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-qty_sold'],
                'indexes': [models.Index(fields=['-qty_sold'], name='Sales_sale_qty_sol_be9d41_idx')],
            },
        ),
    ]
