# Generated by Django 6.0.4 on 2026-06-14 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sales', '0002_alter_sale_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='total_revenue',
            field=models.FloatField(default=0),
        ),
    ]
